name: science_map
description: 科学发展地图

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  http: ^1.1.0
  provider: ^6.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/events/
    - assets/events_index.json
    - assets/story_modes.json