name: science_map
description: 科学发展地图

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  http: ^1.1.0
  provider: ^6.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  url_launcher: ^6.2.0 
  youtube_player_iframe: ^5.1.2 
  flutter_svg: ^2.0.10
  flutter_math_fork: ^0.7.3
  flutter_map_marker_cluster: ^1.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # 确保 'assets:' 部分如下所示
  assets:
    - assets/
    - assets/images/   # 包含您所有的本地图片

    # --- (以下是关键) ---
    # 1. 包含根目录的索引文件
    - assets/events_index.json
    - assets/people_index.json

    # 2. 包含文件夹中的所有 JSON 文件
    # (注意：结尾的 / 斜杠 至关重要!)
    - assets/events/
    - assets/people/